### ISSUE TITLE
How to install inspectIT？

### ISSUE THREAD

**Issue by Yangsheng93** [inspectIT/inspectIT#205]
hi,I consulted a lot of documents, but still do not know how to install. Document does not seem to explain how to install, do you have specific installation steps？My system is CentOS 7.2,There are steps to install it ？
thank you

**Comment by mariomann** [comment]
Hello @Yangsheng93,

thank you for your interest - I will ask your question as detailed as possible:
You can find an ["Installation Guide"](https://inspectit-performance.atlassian.net/wiki/display/DOC17/Installation+Guide) on inspectIT wiki page.

There you can see, how the CMR must be installed, the agent and the UI as well. 
For your system, CentOS 7.2, you can use the installation files for linux systems.

Please let us know if it works. If you have further questions, please contact us.

Greets
Mario

**Comment by ivansenic** [comment]
Hi @Yangsheng93 ,

As @mariomann suggested you need to install inspectIT CMR & UI, and then hook inspectIT agent to your application. Considering you want to have everything on one machine, easiest would be:

1. Grab inspectIT installer for Linux (x64) and run it
2. Start inspectIT CMR: ```./[INSTALL_ROOT]/CMR/startup.sh```
3. Start inspectIT UI: ```./[INSTALL_ROOT]/inspectit/inspectit```
4. Integrate inspectIT agent to your application by adding following Java parameters: ```-javaagent:[INSTALL_ROOT]/agent/inspectit-agent.jar -Dinspectit.repository=localhost:9070 -Dinspectit.agent.name=[AGENT_DISPLAY_NAME]```

That's it basically.. You can consult the documentation for further information about configuration and options.. In addition you can check our [inspectit-labs/workshop](https://github.com/inspectit-labs/workshop) repository that can help in understanding basic functionality.

It would also be valuable to us if you can tell us what was not clear in the documentation you read, so that we can improve it for future users?

**Comment by Yangsheng93** [comment]
Hi ,Excuse me
     In the installation process,prompt the following error(this's UI):
04:50:26.041 [main] DEBUG org.springframework.osgi.extender.internal.activator.ContextLoaderListener - No application context created for bundle [JFace (org.eclipse.jface)]
04:50:26.115 [main] DEBUG org.springframework.osgi.extender.internal.activator.ContextLoaderListener - Scanning bundle [International Components for Unicode for Java (ICU4J) (com.ibm.icu; singleton:=true)] for configurations...
04:50:26.115 [main] DEBUG org.springframework.osgi.extender.internal.activator.ContextLoaderListener - Creating an application context for bundle [International Components for Unicode for Java (ICU4J) (com.ibm.icu; singleton:=true)]
04:50:26.137 [main] DEBUG org.springframework.osgi.extender.internal.activator.ContextLoaderListener - No application context created for bundle [International Components for Unicode for Java (ICU4J) (com.ibm.icu; singleton:=true)]
04:50:26.232 [main] DEBUG org.springframework.osgi.extender.internal.activator.ContextLoaderListener - Scanning bundle [Eclipse UI (org.eclipse.ui; singleton:=true)] for configurations...
04:50:26.232 [main] DEBUG org.springframework.osgi.extender.internal.activator.ContextLoaderListener - Creating an application context for bundle [Eclipse UI (org.eclipse.ui; singleton:=true)]
04:50:26.233 [main] DEBUG org.springframework.osgi.extender.internal.activator.ContextLoaderListener - No application context created for bundle [Eclipse UI (org.eclipse.ui; singleton:=true)]
04:50:26.233 [main] DEBUG org.springframework.osgi.extender.internal.activator.ContextLoaderListener - Scanning bundle [Workbench (org.eclipse.ui.workbench; singleton:=true)] for configurations...
04:50:26.233 [main] DEBUG org.springframework.osgi.extender.internal.activator.ContextLoaderListener - Creating an application context for bundle [Workbench (org.eclipse.ui.workbench; singleton:=true)]
04:50:26.246 [main] DEBUG org.springframework.osgi.extender.internal.activator.ContextLoaderListener - No application context created for bundle [Workbench (org.eclipse.ui.workbench; singleton:=true)]
2016-12-20 04:50:28,007: 2740   [           main] INFO  izer.schema.ClassSchemaManager - ||-Class Schema Manager started..

(inspectIT:2642): Pango-WARNING **: failed to choose a font, expect ugly output. engine-type='PangoRenderFc', script='common'
2016-12-20 04:50:33,363: 8096   [           main] ERROR spectit.ui.rcp.log.LogListener - Could not load SWT style: content/shared.css
java.net.MalformedURLException: no protocol: content/shared.css
	at java.net.URL.<init>(URL.java:589)
	at java.net.URL.<init>(URL.java:486)
	at java.net.URL.<init>(URL.java:435)
	at org.eclipse.ui.internal.intro.impl.swt.SharedStyleManager.load(SharedStyleManager.java:66)
	at org.eclipse.ui.internal.intro.impl.swt.SharedStyleManager.<init>(SharedStyleManager.java:58)
	at org.eclipse.ui.internal.intro.impl.presentations.FormIntroPartImplementation.<init>(FormIntroPartImplementation.java:94)
	at org.eclipse.ui.internal.intro.impl.model.IntroPartPresentation.createPartControl(IntroPartPresentation.java:257)
	at org.eclipse.ui.intro.config.CustomizableIntroPart.createPartControl(CustomizableIntroPart.java:204)
	at org.eclipse.ui.internal.ViewIntroAdapterPart.createPartControl(ViewIntroAdapterPart.java:99)
	at org.eclipse.ui.internal.ViewReference.createPartHelper(ViewReference.java:386)
	at org.eclipse.ui.internal.ViewReference.createPart(ViewReference.java:240)
	at org.eclipse.ui.internal.WorkbenchPartReference.getPart(WorkbenchPartReference.java:595)
	at org.eclipse.ui.internal.Perspective.showView(Perspective.java:2245)
	at org.eclipse.ui.internal.WorkbenchPage.busyShowView(WorkbenchPage.java:1154)
	at org.eclipse.ui.internal.WorkbenchPage$20.run(WorkbenchPage.java:3934)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.ui.internal.WorkbenchPage.showView(WorkbenchPage.java:3931)
	at org.eclipse.ui.internal.WorkbenchPage.showView(WorkbenchPage.java:3907)
	at org.eclipse.ui.internal.WorkbenchIntroManager.createIntro(WorkbenchIntroManager.java:173)
	at org.eclipse.ui.internal.WorkbenchIntroManager.showIntro(WorkbenchIntroManager.java:120)
	at org.eclipse.ui.application.WorkbenchWindowAdvisor.openIntro(WorkbenchWindowAdvisor.java:209)
	at org.eclipse.ui.internal.WorkbenchWindow.open(WorkbenchWindow.java:817)
	at org.eclipse.ui.internal.Workbench$24.runWithException(Workbench.java:1243)
	at org.eclipse.ui.internal.StartupThreading$StartupRunnable.run(StartupThreading.java:31)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3537)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3189)
	at org.eclipse.ui.application.WorkbenchAdvisor.openWindows(WorkbenchAdvisor.java:803)
	at org.eclipse.ui.internal.Workbench$33.runWithException(Workbench.java:1600)
	at org.eclipse.ui.internal.StartupThreading$StartupRunnable.run(StartupThreading.java:31)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3537)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3189)
	at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2609)
	at org.eclipse.ui.internal.Workbench.access$4(Workbench.java:2499)
	at org.eclipse.ui.internal.Workbench$7.run(Workbench.java:679)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:668)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
	at rocks.inspectit.ui.rcp.Application.start(Unknown Source)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:353)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:180)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:629)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:584)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1438)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1414)

   
I am using xmanager in Xmanager - Passive, and garbled.How to solve this problem ？

**Comment by Yangsheng93** [comment]
The problem has already been solved.To perform the following operations：
yum install xorg-x11-font*

thank you help me.

**Comment by pbouillet** [comment]
Hi @Yangsheng93,

as the problem seems to be resolved, I will close the ticket. If you have additional questions / issues, please feel free to open another issue!
