### ISSUE TITLE
Unable to open the latest inspectit.app in Mac OS V11 - java.lang.IllegalStateException: The platform metadata area could not be written: /Applications/inspectIT/inspectit/inspectIT.app/Contents/MacOS/workspace/.metadata. By default the platform writes its content

### ISSUE THREAD

**Issue by dinesh4747** [inspectIT/inspectIT#208]
Unable to open the inspectit app in mac (latest version)

seems some issue in eclipse , please find below log below
```
!SESSION 2016-12-20 22:30:25.254 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.7.0-u80-unofficial
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_US
Framework arguments:  -keyring /Users/z0025g0/.eclipse_keyring -showlocation
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -keyring /Users/z0025g0/.eclipse_keyring -showlocation

!ENTRY org.eclipse.osgi 4 0 2016-12-20 22:30:27.335
!MESSAGE Application error
!STACK 1
java.lang.IllegalStateException: The platform metadata area could not be written: /Applications/inspectIT/inspectit/inspectIT.app/Contents/MacOS/workspace/.metadata.  By default the platform writes its content
under the current working directory when the platform is launched.  Use the -data parameter to
specify a different content area for the platform.
        at org.eclipse.core.internal.runtime.DataArea.assertLocationInitialized(DataArea.java:61)
        at org.eclipse.core.internal.runtime.DataArea.getStateLocation(DataArea.java:125)
        at org.eclipse.core.internal.preferences.InstancePreferences.getBaseLocation(InstancePreferences.java:44)
        at org.eclipse.core.internal.preferences.InstancePreferences.initializeChildren(InstancePreferences.java:199)
        at org.eclipse.core.internal.preferences.InstancePreferences.<init>(InstancePreferences.java:59)
        at org.eclipse.core.internal.preferences.InstancePreferences.internalCreate(InstancePreferences.java:209)
        at org.eclipse.core.internal.preferences.EclipsePreferences.create(EclipsePreferences.java:391)
        at org.eclipse.core.internal.preferences.EclipsePreferences.create(EclipsePreferences.java:379)
        at org.eclipse.core.internal.preferences.PreferencesService.createNode(PreferencesService.java:389)
        at org.eclipse.core.internal.preferences.RootPreferences.getChild(RootPreferences.java:63)
        at org.eclipse.core.internal.preferences.RootPreferences.getNode(RootPreferences.java:101)
        at org.eclipse.core.internal.preferences.RootPreferences.node(RootPreferences.java:90)
        at org.eclipse.core.internal.preferences.AbstractScope.getNode(AbstractScope.java:38)
        at org.eclipse.core.runtime.preferences.InstanceScope.getNode(InstanceScope.java:80)
        at org.eclipse.ui.preferences.ScopedPreferenceStore.getStorePreferences(ScopedPreferenceStore.java:241)
        at org.eclipse.ui.preferences.ScopedPreferenceStore.<init>(ScopedPreferenceStore.java:133)
        at org.eclipse.ui.plugin.AbstractUIPlugin.getPreferenceStore(AbstractUIPlugin.java:285)
        at org.eclipse.ui.internal.UISynchronizer.<init>(UISynchronizer.java:88)
        at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2517)
        at org.eclipse.ui.internal.Workbench.access$4(Workbench.java:2499)
        at org.eclipse.ui.internal.Workbench$7.run(Workbench.java:679)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
        at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:668)
        at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
        at rocks.inspectit.ui.rcp.Application.start(Unknown Source)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
```

**Comment by ivansenic** [comment]
Hi @dinesh4747,

Can you check that the user starting the inspectIT app has the rights to write to the ```/Applications/inspectIT/inspectit/inspectIT.app/Contents/MacOS/``` directory and sub-directories, seams that Eclipse RPC is not able to write configuration stuff there.

In addition you can try to start with the -data parameter pointing to another folder: 
```
./inspectIT -data <workspace_folder>
```

It's also possible to specify the workspace folder in the ```/Applications/inspectIT/inspectit/inspectIT.app/Contents/MacOS/inspectIT.ini``` file by prepending the data parameter before the ```-vmargs``` arguments:
```
-data
<workspace_folder>
-vmargs
-Xmx1024M
-Xms128m
```

**Comment by pbouillet** [comment]
Hi  @dinesh4747 ,

did the hint from @ivansenic work out for you? Is this issue solved?

**Comment by pbouillet** [comment]
Closing this ticket for now. Do not hesitate to reopen or create a new one if you have more questions. Thanks!

**Comment by sushil1992** [comment]
It worked if I moved the application from the Downdload folder to the Applications folder.
