### ISSUE TITLE
Unable to start the the Agent in Tomcat - ERROR java.core.impl.PlatformManager - Server timeout while trying to register something at the server

### ISSUE THREAD

**Issue by dinesh4747** [inspectIT/inspectIT#226]
Hi All -

When i tried out booting my tomcat JVM with InspecIT Agent.jar but somehow it fails due to the below exception on configuration storage throwing exception at "main] ERROR java.core.impl.PlatformManager - Server timeout while trying to register something at the server."

Please find below detailed exception from agents exception log below

2017-01-23 22:57:42,417: 4730   [           main] ERROR java.core.impl.PlatformManager - Server timeout while trying to register something at the server.
2017-01-23 22:57:42,482: 4795   [           main] ERROR spectit.agent.java.SpringAgent - inspectIT agent initialization failed. Agent will not be active.
rocks.inspectit.agent.java.config.StorageException: Agent configuration is not set in the Configuration storage
        at rocks.inspectit.agent.java.config.impl.ConfigurationStorage.ensureConfigurationExists(ConfigurationStorage.java:386)
        at rocks.inspectit.agent.java.config.impl.ConfigurationStorage.isClassCacheExistsOnCmr(ConfigurationStorage.java:320)
        at rocks.inspectit.agent.java.analyzer.impl.ClassHashHelper.afterPropertiesSet(ClassHashHelper.java:219)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1573)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1511)
        ... 35 common frames omitted
Wrapped by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'classHashHelper' defined in URL [jar:file:/agent/inspectit-agent.jar!/rocks/inspectit/agent/java/analyzer/impl/ClassHashHelper.class]: Invocation of init method failed; nested exception is rocks.inspectit.agent.java.config.StorageException: Agent configuration is not set in the Configuration storage
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1514)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:521)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:458)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:293)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:223)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:290)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:191)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:921)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:864)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:779)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:503)
        ... 25 common frames omitted
Wrapped by: org.springframework.beans.factory.BeanCreationException: Could not autowire field: private rocks.inspectit.agent.java.analyzer.impl.ClassHashHelper rocks.inspectit.agent.java.instrumentation.RetransformManager.classHashHelper; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'classHashHelper' defined in URL [jar:file:/agent/inspectit-agent.jar!/rocks/inspectit/agent/java/analyzer/impl/ClassHashHelper.class]: Invocation of init method failed; nested exception is rocks.inspectit.agent.java.config.StorageException: Agent configuration is not set in the Configuration storage
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:531)
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:295)
        ... 23 common frames omitted
Wrapped by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'retransformManager': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private rocks.inspectit.agent.java.analyzer.impl.ClassHashHelper rocks.inspectit.agent.java.instrumentation.RetransformManager.classHashHelper; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'classHashHelper' defined in URL [jar:file:/agent/inspectit-agent.jar!/rocks/inspectit/agent/java/analyzer/impl/ClassHashHelper.class]: Invocation of init method failed; nested exception is rocks.inspectit.agent.java.config.StorageException: Agent configuration is not set in the Configuration storage

**Comment by pbouillet** [comment]
Hi @dinesh4747 ,

do you have a configuration defined for the agent in the UI? Please check also your agent mapping. Seems like the agent cannot get its configuration from the CMR.

**Comment by dinesh4747** [comment]
HI @pbouillet 

Yes when i referred to my CMR log i found the below exception

2017-01-23 22:57:39,434: 77909215 [         Server] ERROR tit.minlog.MinlogToSLF4JLogger - kryonet: Error reading TCP from connection: Connection 1
com.esotericsoftware.kryo.KryoException: Invalid method index 4 for class: info.novatec.inspectit.cmr.service.IAgentStorageService
        at info.novatec.inspectit.kryonet.rmi.ObjectSpace$InvokeMethod.read(ObjectSpace.java:588) ~[inspectit-commons.jar:na]
        at com.esotericsoftware.kryo.serializers.DefaultSerializers$KryoSerializableSerializer.read(DefaultSerializers.java:433) ~[kryo-2.24.0.jar:na]
        at com.esotericsoftware.kryo.serializers.DefaultSerializers$KryoSerializableSerializer.read(DefaultSerializers.java:425) ~[kryo-2.24.0.jar:na]
        at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:761) ~[kryo-2.24.0.jar:na]
        at info.novatec.inspectit.kryonet.ExtendedSerializationImpl.read(ExtendedSerializationImpl.java:156) ~[inspectit-commons.jar:na]
        at info.novatec.inspectit.kryonet.TcpConnection.readObject(TcpConnection.java:187) ~[inspectit-commons.jar:na]
Wrapped by: com.esotericsoftware.kryonet.KryoNetException: Error during deserialization.
        at info.novatec.inspectit.kryonet.TcpConnection.readObject(TcpConnection.java:189) ~[inspectit-commons.jar:na]
        at info.novatec.inspectit.kryonet.Server.update(Server.java:231) [inspectit-commons.jar:na]
        at info.novatec.inspectit.kryonet.Server.run(Server.java:406) [inspectit-commons.jar:na]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_51]

**Comment by pbouillet** [comment]
This on the other hand seems like that the version of the Agent and CMR differ. What does the Agent and CMR say about the version on startup? Should be in the logs.

**Comment by dinesh4747** [comment]
2017-01-24 01:55:24,597: 245    [           main] WARN  info.novatec.inspectit.cmr.CMR - ATTENTION: The version of this JVM (1.8.0_51) is not compatible with the CMR! Please use the JVM that is provided with the installation!

**Comment by dinesh4747** [comment]
I could see the detailed logs under /CMR/logs/exceptions.log as below

2017-01-24 01:55:24,597: 245    [           main] WARN  info.novatec.inspectit.cmr.CMR - ATTENTION: The version of this JVM (1.8.0_51) is not compatible with the CMR! Please use the JVM that is provided with the installation!
2017-01-24 01:56:16,007: 216    [           main] WARN  info.novatec.inspectit.cmr.CMR - ATTENTION: The version of this JVM (1.8.0_51) is not compatible with the CMR! Please use the JVM that is provided with the installation!
2017-01-24 01:59:02,466: 166675 [         Server] ERROR tit.minlog.MinlogToSLF4JLogger - kryonet: Error reading TCP from connection: Connection 1
com.esotericsoftware.kryo.KryoException: Invalid method index 4 for class: info.novatec.inspectit.cmr.service.IAgentStorageService
        at info.novatec.inspectit.kryonet.rmi.ObjectSpace$InvokeMethod.read(ObjectSpace.java:588) ~[inspectit-commons.jar:na]
        at com.esotericsoftware.kryo.serializers.DefaultSerializers$KryoSerializableSerializer.read(DefaultSerializers.java:433) ~[kryo-2.24.0.jar:na]
        at com.esotericsoftware.kryo.serializers.DefaultSerializers$KryoSerializableSerializer.read(DefaultSerializers.java:425) ~[kryo-2.24.0.jar:na]
        at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:761) ~[kryo-2.24.0.jar:na]
        at info.novatec.inspectit.kryonet.ExtendedSerializationImpl.read(ExtendedSerializationImpl.java:156) ~[inspectit-commons.jar:na]
        at info.novatec.inspectit.kryonet.TcpConnection.readObject(TcpConnection.java:187) ~[inspectit-commons.jar:na]
Wrapped by: com.esotericsoftware.kryonet.KryoNetException: Error during deserialization.
        at info.novatec.inspectit.kryonet.TcpConnection.readObject(TcpConnection.java:189) ~[inspectit-commons.jar:na]
        at info.novatec.inspectit.kryonet.Server.update(Server.java:231) [inspectit-commons.jar:na]
        at info.novatec.inspectit.kryonet.Server.run(Server.java:406) [inspectit-commons.jar:na]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_51]

**Comment by dinesh4747** [comment]
My Application (Tomcat JVM) is running on openjdk version "1.8.0_51"

When i Try to run the CMR also with the same JVM I am getting the above issue 

I want to understand on whether CMR will not be compatible with above OpenJDK Version 1.8u51 

If that is the case what i should be doing to mitigate this - please do help me in guiding me in this regard

**Comment by pbouillet** [comment]
Sorry about the confusion, I was talking about the version of inspectIT of the agent and CMR, not the JVM version. This should be printed upon startup in the beginning of the log. Could you check this please?

About the JVM: Why do you want to run the CMR with your JVM? Is there a reason? It is advisable to use the provided one if possible. There could be otherwise some issues that occur.

**Comment by dinesh4747** [comment]
HI @pbouillet 

There was a mismatch in Agent and CMR Version because of which it failed 

Currently its working fine and i could able to connect Agent and CMR successfully 

One more question:

Does InspectIT Supports Apache Httpd Server/Web server (It doesn't run on any JVM) and runs as a plain process

**Comment by pbouillet** [comment]
Good to hear that it works now!

About apache httpd: Not as in we do provide traces or detailed information. But in the overall picture, you can get information from the web server into the monitoring data. This is done through a collectd integration into grafana / influxdb:
https://collectd.org/
https://inspectit-performance.atlassian.net/wiki/display/DOC17/Allow+data+collection+with+inspectIT+collectd+Integration
https://inspectit-performance.atlassian.net/wiki/display/DOC17/Setup+longterm+database

**Comment by dinesh4747** [comment]
HI @pbouillet 

Sounds like an interesting stuff 

I shall surely try out setting up Grafana/Influx Integration 

For Now I am closing the issue since my orginal issue is resolved

Thanks for your assistance here
