### ISSUE TITLE
Client throws Null Pointer Exception while we try to access URI Aggregation details

### ISSUE THREAD

**Issue by youjenli** [inspectIT/inspectIT#241]
If we right click a URL in `URI Aggregation` view and click `Details`....  

![1 7 8 91-client-access-url-agg-details](https://cloud.githubusercontent.com/assets/1283378/23788832/48f39f96-05b3-11e7-842e-6502f88a7720.png)

Then Inspectit client will pop up a Null Pointer Exception.

![1 7 8 91-url-aggregate-detail-view-error](https://cloud.githubusercontent.com/assets/1283378/23788829/43968ee6-05b3-11e7-98b2-7006e006d4de.png)

Exception Stack Trace:
```
inspectIT Version: 1.7.8.91  
Operating system: Windows 7 6.1 (amd64)  
Java version: Oracle Corporation 1.7.0-u80-unofficial  
Exception type: java.lang.NullPointerException  
Exception message: null  
Stack trace (limited): java.lang.NullPointerException  
        at rocks.inspectit.ui.rcp.details.generator.impl.HttpDetailsGenerator.generate(Unknown Source)  
        at rocks.inspectit.ui.rcp.details.DetailsGenerationFactory.createDetailComposites(Unknown Source)  
        at rocks.inspectit.ui.rcp.dialog.DetailsDialog.createDialogArea(Unknown Source)  
        at org.eclipse.jface.dialogs.Dialog.createContents(Dialog.java:760)  
        at org.eclipse.jface.window.Window.create(Window.java:431)  
        at org.eclipse.jface.dialogs.Dialog.create(Dialog.java:1089)  
        at org.eclipse.jface.window.Window.open(Window.java:790)  
        at rocks.inspectit.ui.rcp.handlers.DetailsHandler.execute(Unknown Source)  
        at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:290)  
        at org.eclipse.core.commands.Command.executeWithChecks(Command.java:499)  
        at  org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:508)  
        at org.eclipse.ui.internal.handlers.HandlerService.executeCommand(HandlerService.java:169)  
        at org.e ...  
```

**Comment by pbouillet** [comment]
Thanks for the report, I create a Jira ticket for this and already reproduced it locally:
https://inspectit-performance.atlassian.net/browse/INSPECTIT-2340
