### ISSUE TITLE
Client throws Exception for the first time we focus on any view in Configuration Perspective.

### ISSUE THREAD

**Issue by youjenli** [inspectIT/inspectIT#243]
The InspectIT **1.7.8.91** client pop up Exception widget repeatedly for the first time we focus on the `Instrumentation Manager`, `Business Context Manager`, `Alert Manager` view in `Configuration Perspective`.  

### The Instrumentation Manager case:
![localcmr instrument](https://cloud.githubusercontent.com/assets/1283378/23846127/d31144c6-0806-11e7-9e67-f9e589d41bc5.png)
**Error report**:
```
inspectIT Version: 1.7.8.91 
Operating system: Windows 7 6.1 (amd64) 
Java version: Oracle Corporation 1.7.0-u80-unofficial
Exception type: org.springframework.remoting.RemoteAccessException 
Exception message: Could not access HTTP invoker remote service at [http://localhost:8182/remoting/ConfigurationInterfaceService]; nested exception is java.lang.InstantiationError: rocks.inspectit.shared.cs.ci.business.expression.AbstractExpression
Stack trace (limited): org.springframework.remoting.RemoteAccessException: Could not access HTTP invoker remote service at [http://localhost:8182/remoting/ConfigurationInterfaceService]; nested exception is java.lang.InstantiationError: rocks.inspectit.shared.cs.ci.business.expression.AbstractExpression
        at org.springframework.remoting.httpinvoker.HttpInvokerClientInterceptor.convertHttpInvokerAccessException(HttpInvokerClientInterceptor.java:213)
        at org.springframework.remoting.httpinvoker.HttpInvokerClientInterceptor.invoke(HttpInvokerClientInterceptor.java:145)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) 
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204) 
        at com.sun.proxy.$Proxy52.getAllProfiles(Unknown Source) 
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) 
        at sun.reflect.DelegatingMethodAcce 
```

### The Business Context Manager case:
![localcmr business_context_manager](https://cloud.githubusercontent.com/assets/1283378/23846718/bb14d4ca-0809-11e7-8abf-d6d383fa4b3f.png)
**Error report**:
```
Exception type: org.springframework.remoting.RemoteInvocationFailureException 
Exception message: Invocation of method [public abstract java.util.List rocks.inspectit.shared.cs.cmr.service.IConfigurationInterfaceService.getApplicationDefinitions()] failed in HTTP invoker remote service at [http://localhost:8182/remoting/ConfigurationInterfaceService]; nested exception is java.lang.NoSuchMethodException: com.sun.proxy.$Proxy101.getApplicationDefinitions()
Stack trace (limited): org.springframework.remoting.RemoteInvocationFailureException: Invocation of method [public abstract java.util.List rocks.inspectit.shared.cs.cmr.service.IConfigurationInterfaceService.getApplicationDefinitions()] failed in HTTP invoker remote service at [http://localhost:8182/remoting/ConfigurationInterfaceService]; nested exception is java.lang.NoSuchMethodException: com.sun.proxy.$Proxy101.getApplicationDefinitions()
        at org.springframework.remoting.httpinvoker.HttpInvokerClientInterceptor.invoke(HttpInvokerClientInterceptor.java:155)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) 
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204) 
        at com.sun.proxy.$Proxy52.getApplicationDefinitions(Unknown Source) 
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) 
        at sun.reflect.DelegatingMetho 
```

### The Alert Manager case:
![localcmr alert manager](https://cloud.githubusercontent.com/assets/1283378/23846149/f1e59c12-0806-11e7-96aa-d0e32daaaa14.png)
**Error report**:
```
Exception type: org.springframework.remoting.RemoteInvocationFailureException 
Exception message: Invocation of method [public abstract java.util.List rocks.inspectit.shared.cs.cmr.service.IConfigurationInterfaceService.getAlertingDefinitions()] failed in HTTP invoker remote service at [http://localhost:8182/remoting/ConfigurationInterfaceService]; nested exception is java.lang.NoSuchMethodException: com.sun.proxy.$Proxy101.getAlertingDefinitions()
Stack trace (limited): org.springframework.remoting.RemoteInvocationFailureException: Invocation of method [public abstract java.util.List rocks.inspectit.shared.cs.cmr.service.IConfigurationInterfaceService.getAlertingDefinitions()] failed in HTTP invoker remote service at [http://localhost:8182/remoting/ConfigurationInterfaceService]; nested exception is java.lang.NoSuchMethodException: com.sun.proxy.$Proxy101.getAlertingDefinitions()
        at org.springframework.remoting.httpinvoker.HttpInvokerClientInterceptor.invoke(HttpInvokerClientInterceptor.java:155)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) 
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204) 
        at com.sun.proxy.$Proxy52.getAlertingDefinitions(Unknown Source) 
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) 
        at sun.reflect.DelegatingMethodAccessor 
```

I believe this is because the client does not handle exception properly when it is not able to receive data from a no-agent-connected CMR (Local CMR).

**Comment by pbouillet** [comment]
Which version of the CMR is running? Can you paste the CMR logs please?

**Comment by youjenli** [comment]
@pbouillet 
I believe it is the `Local CMR` which was bundled with InspectIT client.

**Comment by pbouillet** [comment]
Can you go to the repository manager, select the Local CMR and past the Version it displays in the bottom view?

**Comment by youjenli** [comment]
The Client pop up `SerializationException`.

![de-serialization](https://cloud.githubusercontent.com/assets/1283378/23847437/401fc0be-080d-11e7-8418-ef6996dfd347.png)
**Error report**:
```
inspectIT Version: 1.7.8.91 
Operating system: Windows 7 6.1 (amd64) 
Java version: Oracle Corporation 1.7.0-u80-unofficial 
Exception type: rocks.inspectit.shared.all.serializer.SerializationException 
Exception message: De-serialization failed. 
Encountered unregistered class ID: 1197635070 
Serialization trace: 
externalServiceStatusMap (rocks.inspectit.shared.all.communication.data.cmr.CmrStatusData) 
value (org.springframework.remoting.support.RemoteInvocationResult) 
Stack trace (limited): rocks.inspectit.shared.all.serializer.SerializationException: De-serialization failed. 
Encountered unregistered class ID: 1197635070 
Serialization trace: 
externalServiceStatusMap (rocks.inspectit.shared.all.communication.data.cmr.CmrStatusData) 
value (org.springframework.remoting.support.RemoteInvocationResult) 
        at rocks.inspectit.shared.all.serializer.impl.SerializationManager.deserialize(SerializationManager.java:437) 
        at rocks.inspectit.ui.rcp.repository.service.cmr.KryoSimpleHttpInvokerRequestExecutor.readRemoteInvocationResult(Unknown Source)
        at org.springframework.remoting.httpinvoker.SimpleHttpInvokerRequestExecutor.doExecuteRequest(SimpleHttpInvokerRequestExecutor.java:95)
        at org.springframework.remoting.httpinvoker.AbstractHttpInvokerRequestExecutor.executeRequest(AbstractHttpInvokerRequestExecutor.java:136)
        at org.springframework.remoting.httpinvoker.HttpInvokerClientInterceptor.executeRequest(HttpInvokerClientInterceptor.java:192)
        at org.springframework.remoting.ht 
```

**Comment by pbouillet** [comment]
It really seems like you have an old version of the CMR running locally. Can you please check if this is the case and run the newest version? It has to be the same version as the UI + agent, otherwise these exceptions will occur.

**Comment by youjenli** [comment]
How to find out which version of Local CMR is running now?  
I have separated every installations of Inspect client in my PC, but I don't know where did they store the executable of Local CMR.

**Comment by pbouillet** [comment]
How is the CMR started? Through the windows start menu? Or manually? Either way, just try to find out where it points to and take a look at the logs in the contained logs folder.

**Comment by youjenli** [comment]
I just open the installation directory of ver 1.7.8.91 and execute the `inspectIT.exe`.  
It seems that the client start Local CMR automatically.  
I have uploaded [log files][log files] of client for your investigation.  

[log files]: https://drive.google.com/drive/folders/0BxfRIIL6wqYuNXcxTG9PMVZlTmM?usp=sharing "Log files"

By the way, we are using HTTP Proxy to connect to websites outside our company.   
Do you think this issue may be related to proxy settings?

**Comment by pbouillet** [comment]
The UI and Server / CMR are completely unrelated. There is no automation that a local server is started just by opening the UI. Thus you have a local server running and I assume an old one. Do you even need it? If not, just deinstall the old server and remove it from the UI and the error is gone.

**Comment by youjenli** [comment]
Oh... you are right.  
I forgot I have create an old version CMR locally.  
Now I have resolve this issue, thank you!

**Comment by pbouillet** [comment]
Awesome :grinning: . I'll close the issue then. If you have further questions and problems, just reopen or create a new issue!
