### ISSUE TITLE
getting error while installing inspectIT UI

### ISSUE THREAD

**Issue by rohit067** [inspectIT/inspectIT#350]
error :
10:25:15.360 [Start Level Event Dispatcher] INFO org.springframework.osgi.extender.internal.activator.ContextLoaderListener -Starting [org.springframework.osgi.extender] bundle v.[1.2.1]
10:25:15.420 [Start Level Event Dispatcher] DEBUG org.springframework.osgi.extender.internal.support.NamespaceManager - Addin namespace handler resolver for spring-osgi-core (org.springframework.osgi.core)
10:25:15.420 [Start Level Event Dispatcher] DEBUG org.springframework.osgi.extender.internal.support.NamespacePlugins - Addin as handler spring-osgi-core (org.springframework.osgi.core)
10:25:15.425 [Start Level Event Dispatcher] DEBUG org.springframework.osgi.extender.internal.support.NamespaceManager - Addin namespace handler resolver for org.springframework.spring-aop (org.springframework.spring-aop)
10:25:15.426 [Start Level Event Dispatcher] DEBUG org.springframework.osgi.extender.internal.support.NamespacePlugins - Addin as handler org.springframework.spring-aop (org.springframework.spring-aop)
10:25:15.426 [Start Level Event Dispatcher] DEBUG org.springframework.osgi.extender.internal.support.NamespaceManager - Addin namespace handler resolver for org.springframework.spring-beans (org.springframework.spring-beans)
10:25:15.426 [Start Level Event Dispatcher] DEBUG org.springframework.osgi.extender.internal.support.NamespacePlugins - Addin as handler org.springframework.spring-beans (org.springframework.spring-beans)
10:25:15.426 [Start Level Event Dispatcher] DEBUG org.springframework.osgi.extender.internal.support.NamespaceManager - Addin namespace handler resolver for org.springframework.spring-context (org.springframework.spring-context)
10:25:15.426 [Start Level Event Dispatcher] DEBUG org.springframework.osgi.extender.internal.support.NamespacePlugins - Addin as handler org.springframework.spring-context (org.springframework.spring-context)
10:25:15.433 [Start Level Event Dispatcher] DEBUG org.springframework.osgi.extender.internal.support.NamespaceManager - Regisering Spring NamespaceHandlerResolver and EntityResolver...
10:25:15.438 [Start Level Event Dispatcher] INFO org.springframework.osgi.extender.internal.support.ExtenderConfiguration - N custom extender configuration detected; using defaults...
10:25:15.444 [Start Level Event Dispatcher] INFO org.springframework.scheduling.timer.TimerTaskExecutor - Initializing Timer
10:25:15.453 [Start Level Event Dispatcher] DEBUG org.springframework.osgi.extender.internal.support.ExtenderConfiguration - pring-DM annotation processing disabled; [org.springframework.osgi.extensions.annotation.ServiceReferenceDependencyBeanFactorPostProcessor] not loaded
10:25:15.493 [Start Level Event Dispatcher] DEBUG org.springframework.osgi.service.importer.support.StaticServiceProxyCreator- Greedy proxying will NOT consider exposed classes
10:25:15.494 [Start Level Event Dispatcher] DEBUG org.springframework.osgi.service.importer.support.OsgiServiceCollectionProxFactoryBean - Creating a multi-value/collection proxy
10:25:15.501 [Start Level Event Dispatcher] DEBUG org.springframework.osgi.extender.internal.activator.ContextLoaderListener  Initialization of OSGi listeners service completed...
10:25:15.505 [Start Level Event Dispatcher] DEBUG org.springframework.osgi.extender.internal.activator.ContextLoaderListener  Scanning bundle [Eclipse Content Mechanism (org.eclipse.core.contenttype; singleton:=true)] for configurations...
10:25:15.505 [Start Level Event Dispatcher] DEBUG org.springframework.osgi.extender.internal.activator.ContextLoaderListener  Creating an application context for bundle [Eclipse Content Mechanism (org.eclipse.core.contenttype; singleton:=true)]
10:25:15.507 [Start Level Event Dispatcher] DEBUG org.springframework.osgi.extender.internal.activator.ContextLoaderListener  No application context created for bundle [Eclipse Content Mechanism (org.eclipse.core.contenttype; singleton:=true)]
10:25:15.507 [Start Level Event Dispatcher] DEBUG org.springframework.osgi.extender.internal.activator.ContextLoaderListener  Scanning bundle [Eclipse Jobs Mechanism (org.eclipse.core.jobs; singleton:=true)] for configurations...
10:25:15.507 [Start Level Event Dispatcher] DEBUG org.springframework.osgi.extender.internal.activator.ContextLoaderListener  Creating an application context for bundle [Eclipse Jobs Mechanism (org.eclipse.core.jobs; singleton:=true)]
10:25:15.507 [Start Level Event Dispatcher] DEBUG org.springframework.osgi.extender.internal.activator.ContextLoaderListener  No application context created for bundle [Eclipse Jobs Mechanism (org.eclipse.core.jobs; singleton:=true)]
10:25:15.507 [Start Level Event Dispatcher] DEBUG org.springframework.osgi.extender.internal.activator.ContextLoaderListener  Scanning bundle [Core Runtime (org.eclipse.core.runtime; singleton:=true)] for configurations...
10:25:15.507 [Start Level Event Dispatcher] DEBUG org.springframework.osgi.extender.internal.activator.ContextLoaderListener  Creating an application context for bundle [Core Runtime (org.eclipse.core.runtime; singleton:=true)]
10:25:15.508 [Start Level Event Dispatcher] DEBUG org.springframework.osgi.extender.internal.activator.ContextLoaderListener  No application context created for bundle [Core Runtime (org.eclipse.core.runtime; singleton:=true)]
10:25:15.508 [Start Level Event Dispatcher] DEBUG org.springframework.osgi.extender.internal.activator.ContextLoaderListener  Scanning bundle [Equinox Application Container (org.eclipse.equinox.app; singleton:=true)] for configurations...
10:25:15.508 [Start Level Event Dispatcher] DEBUG org.springframework.osgi.extender.internal.activator.ContextLoaderListener  Creating an application context for bundle [Equinox Application Container (org.eclipse.equinox.app; singleton:=true)]
10:25:15.508 [Start Level Event Dispatcher] DEBUG org.springframework.osgi.extender.internal.activator.ContextLoaderListener  No application context created for bundle [Equinox Application Container (org.eclipse.equinox.app; singleton:=true)]
10:25:15.508 [Start Level Event Dispatcher] DEBUG org.springframework.osgi.extender.internal.activator.ContextLoaderListener  Scanning bundle [Common Eclipse Runtime (org.eclipse.equinox.common; singleton:=true)] for configurations...
10:25:15.508 [Start Level Event Dispatcher] DEBUG org.springframework.osgi.extender.internal.activator.ContextLoaderListener  Creating an application context for bundle [Common Eclipse Runtime (org.eclipse.equinox.common; singleton:=true)]
10:25:15.508 [Start Level Event Dispatcher] DEBUG org.springframework.osgi.extender.internal.activator.ContextLoaderListener  No application context created for bundle [Common Eclipse Runtime (org.eclipse.equinox.common; singleton:=true)]
10:25:15.509 [Start Level Event Dispatcher] DEBUG org.springframework.osgi.extender.internal.activator.ContextLoaderListener  Scanning bundle [Eclipse Preferences Mechanism (org.eclipse.equinox.preferences; singleton:=true)] for configurations...
10:25:15.509 [Start Level Event Dispatcher] DEBUG org.springframework.osgi.extender.internal.activator.ContextLoaderListener  Creating an application context for bundle [Eclipse Preferences Mechanism (org.eclipse.equinox.preferences; singleton:=true)
10:25:15.509 [Start Level Event Dispatcher] DEBUG org.springframework.osgi.extender.internal.activator.ContextLoaderListener  No application context created for bundle [Eclipse Preferences Mechanism (org.eclipse.equinox.preferences; singleton:=true)]
10:25:15.509 [Start Level Event Dispatcher] DEBUG org.springframework.osgi.extender.internal.activator.ContextLoaderListener  Scanning bundle [Extension Registry Support (org.eclipse.equinox.registry;singleton:=true)] for configurations...
10:25:15.509 [Start Level Event Dispatcher] DEBUG org.springframework.osgi.extender.internal.activator.ContextLoaderListener  Creating an application context for bundle [Extension Registry Support (org.eclipse.equinox.registry;singleton:=true)]
10:25:15.510 [Start Level Event Dispatcher] DEBUG org.springframework.osgi.extender.internal.activator.ContextLoaderListener  No application context created for bundle [Extension Registry Support (org.eclipse.equinox.registry;singleton:=true)]
10:25:15.511 [Start Level Event Dispatcher] DEBUG org.springframework.osgi.extender.internal.activator.ContextLoaderListener  Scanning bundle [OSGi System Bundle (org.eclipse.osgi; singleton:=true)] for configurations...
10:25:15.511 [Start Level Event Dispatcher] DEBUG org.springframework.osgi.extender.internal.activator.ContextLoaderListener  Creating an application context for bundle [OSGi System Bundle (org.eclipse.osgi; singleton:=true)]
10:25:15.514 [Start Level Event Dispatcher] DEBUG org.springframework.osgi.extender.internal.activator.ContextLoaderListener  No application context created for bundle [OSGi System Bundle (org.eclipse.osgi; singleton:=true)]
10:25:15.534 [main] DEBUG org.springframework.osgi.extender.internal.activator.ContextLoaderListener - Scanning bundle [JFace(org.eclipse.jface)] for configurations...
10:25:15.534 [main] DEBUG org.springframework.osgi.extender.internal.activator.ContextLoaderListener - Creating an applicatio context for bundle [JFace (org.eclipse.jface)]
10:25:15.538 [main] DEBUG org.springframework.osgi.extender.internal.activator.ContextLoaderListener - No application contextcreated for bundle [JFace (org.eclipse.jface)]
10:25:15.604 [main] DEBUG org.springframework.osgi.extender.internal.activator.ContextLoaderListener - Scanning bundle [Interational Components for Unicode for Java (ICU4J) (com.ibm.icu; singleton:=true)] for configurations...
10:25:15.604 [main] DEBUG org.springframework.osgi.extender.internal.activator.ContextLoaderListener - Creating an applicatio context for bundle [International Components for Unicode for Java (ICU4J) (com.ibm.icu; singleton:=true)]
10:25:15.622 [main] DEBUG org.springframework.osgi.extender.internal.activator.ContextLoaderListener - No application contextcreated for bundle [International Components for Unicode for Java (ICU4J) (com.ibm.icu; singleton:=true)]
10:25:15.675 [main] DEBUG org.springframework.osgi.extender.internal.activator.ContextLoaderListener - Scanning bundle [Eclipe UI (org.eclipse.ui; singleton:=true)] for configurations...
10:25:15.675 [main] DEBUG org.springframework.osgi.extender.internal.activator.ContextLoaderListener - Creating an applicatio context for bundle [Eclipse UI (org.eclipse.ui; singleton:=true)]
10:25:15.676 [main] DEBUG org.springframework.osgi.extender.internal.activator.ContextLoaderListener - No application contextcreated for bundle [Eclipse UI (org.eclipse.ui; singleton:=true)]
10:25:15.737 [main] DEBUG org.springframework.osgi.extender.internal.activator.ContextLoaderListener - Scanning bundle [Workbnch (org.eclipse.ui.workbench; singleton:=true)] for configurations...
10:25:15.737 [main] DEBUG org.springframework.osgi.extender.internal.activator.ContextLoaderListener - Creating an applicatio context for bundle [Workbench (org.eclipse.ui.workbench; singleton:=true)]
10:25:15.747 [main] DEBUG org.springframework.osgi.extender.internal.activator.ContextLoaderListener - No application contextcreated for bundle [Workbench (org.eclipse.ui.workbench; singleton:=true)]
InspectIT:
An error has occurred. See the log file
/aflac/inspectit/inspectit/workspace/.metadata/.log.

**Comment by ivansenic** [comment]
Can you provide us with the content of the ```/aflac/inspectit/inspectit/workspace/.metadata/.log.```?

**Comment by rohit067** [comment]
I can't see anything in /aflac/inspectit/inspectit/workspace/.metadata/.log.?

**Comment by rohit067** [comment]
below is the content of /aflac/inspectit/inspectit/workspace/.metadata/.log.?


!SESSION 2017-08-31 10:25:10.647 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.7.0-u80-unofficial
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64

!ENTRY org.eclipse.osgi 4 0 2017-08-31 10:25:18.724
!MESSAGE Application error
!STACK 1
org.eclipse.swt.SWTError: No more handles [gtk_init_check() failed]
        at org.eclipse.swt.SWT.error(SWT.java:4387)
        at org.eclipse.swt.widgets.Display.createDisplay(Display.java:914)
        at org.eclipse.swt.widgets.Display.create(Display.java:900)
        at org.eclipse.swt.graphics.Device.<init>(Device.java:156)
        at org.eclipse.swt.widgets.Display.<init>(Display.java:498)
        at org.eclipse.swt.widgets.Display.<init>(Display.java:489)
        at org.eclipse.ui.internal.Workbench.createDisplay(Workbench.java:716)
        at org.eclipse.ui.PlatformUI.createDisplay(PlatformUI.java:161)
        at rocks.inspectit.ui.rcp.Application.start(Unknown Source)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:353)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:180)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:629)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:584)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1438)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1414)
!SESSION 2017-08-31 12:01:45.408 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.7.0-u80-unofficial
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64

!ENTRY org.eclipse.osgi 4 0 2017-08-31 12:01:56.002
!MESSAGE Application error
!STACK 1
org.eclipse.swt.SWTError: No more handles [gtk_init_check() failed]
        at org.eclipse.swt.SWT.error(SWT.java:4387)
        at org.eclipse.swt.widgets.Display.createDisplay(Display.java:914)
        at org.eclipse.swt.widgets.Display.create(Display.java:900)
        at org.eclipse.swt.graphics.Device.<init>(Device.java:156)
        at org.eclipse.swt.widgets.Display.<init>(Display.java:498)
        at org.eclipse.swt.widgets.Display.<init>(Display.java:489)
        at org.eclipse.ui.internal.Workbench.createDisplay(Workbench.java:716)
        at org.eclipse.ui.PlatformUI.createDisplay(PlatformUI.java:161)
        at rocks.inspectit.ui.rcp.Application.start(Unknown Source)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:353)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:180)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:629)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:584)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1438)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1414)

**Comment by andreasreinhardt** [comment]
I had the same problem once with Eclipse. Only a restart of Linux helped.

**Comment by ivansenic** [comment]
@rohit067 Are you trying to run this on the Desktop based OS? Our UI is a Eclipse-based application and I see that for you the ```gtk_init_check() failed```, thus let's just confirm that you are trying to start this on the machine where it can be run :smile:
