### ISSUE TITLE
Problem in installing InspectIT CMR

### ISSUE THREAD

**Issue by charly13887** [inspectIT/inspectIT#373]
Hi,

While Installing InspectIT CMR version 1.7.11.94. While starting CMR we are getting below error.

```
2017-11-08 23:19:28,290: 543087 [           main] ERROR ne.jdbc.spi.SqlExceptionHelper - Connections could not be acquired from the underlying database!
2017-11-08 23:19:28,304: 543101 [           main] ERROR            java.lang.Throwable - Exception in thread "main" org.springframework.beans.factory.access.BootstrapException: Unable to initialize group definition. Group resource name [classpath*:beanRefContext.xml], factory key [ctx]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'ctx' defined in URL [jar:file:/C:/Program%20Files%20(x86)/inspectIT/CMR/inspectit-cmr.jar!/beanRefContext.xml]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [org.springframework.context.support.ClassPathXmlApplicationContext]: Constructor threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [spring/spring-context-database.xml]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: [PersistenceUnit: DefaultPersistenceUnit] Unable to build Hibernate SessionFactory
2017-11-08 23:19:28,332: 543129 [           main] ERROR            java.lang.Throwable -        at org.springframework.beans.factory.access.SingletonBeanFactoryLocator.useBeanFactory(SingletonBeanFactoryLocator.java:386)
2017-11-08 23:19:28,336: 543133 [           main] ERROR            java.lang.Throwable -        at rocks.inspectit.server.CMR.startRepository(CMR.java:95)
2017-11-08 23:19:28,339: 543136 [           main] ERROR            java.lang.Throwable -        at rocks.inspectit.server.CMR.startCMR(CMR.java:81)
2017-11-08 23:19:28,342: 543139 [           main] ERROR            java.lang.Throwable -        at rocks.inspectit.server.CMR.main(CMR.java:240)
2017-11-08 23:19:28,347: 543144 [           main] ERROR            java.lang.Throwable - Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'ctx' defined in URL [jar:file:/C:/Program%20Files%20(x86)/inspectIT/CMR/inspectit-cmr.jar!/beanRefContext.xml]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [org.springframework.context.support.ClassPathXmlApplicationContext]: Constructor threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [spring/spring-context-database.xml]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: [PersistenceUnit: DefaultPersistenceUnit] Unable to build Hibernate SessionFactory
2017-11-08 23:19:28,368: 543165 [           main] ERROR            java.lang.Throwable -        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:285)
2017-11-08 23:19:28,373: 543170 [           main] ERROR            java.lang.Throwable -        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1077)
2017-11-08 23:19:28,378: 543175 [           main] ERROR            java.lang.Throwable -        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:981)
2017-11-08 23:19:28,384: 543181 [           main] ERROR            java.lang.Throwable -        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:487)
2017-11-08 23:19:28,389: 543186 [           main] ERROR            java.lang.Throwable -        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:458)
2017-11-08 23:19:28,394: 543191 [           main] ERROR            java.lang.Throwable -        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:293)
2017-11-08 23:19:28,400: 543197 [           main] ERROR            java.lang.Throwable -        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:223)
2017-11-08 23:19:28,406: 543203 [           main] ERROR            java.lang.Throwable -        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:290)
2017-11-08 23:19:28,413: 543210 [           main] ERROR            java.lang.Throwable -        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:191)
2017-11-08 23:19:28,423: 543220 [           main] ERROR            java.lang.Throwable -        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:636)
2017-11-08 23:19:28,431: 543228 [           main] ERROR            java.lang.Throwable -        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:938)
2017-11-08 23:19:28,437: 543234 [           main] ERROR            java.lang.Throwable -        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:479)
2017-11-08 23:19:28,445: 543242 [           main] ERROR            java.lang.Throwable -        at org.springframework.context.access.ContextSingletonBeanFactoryLocator.initializeDefinition(ContextSingletonBeanFactoryLocator.java:143)
2017-11-08 23:19:28,455: 543252 [           main] ERROR            java.lang.Throwable -        at org.springframework.beans.factory.access.SingletonBeanFactoryLocator.useBeanFactory(SingletonBeanFactoryLocator.java:381)
2017-11-08 23:19:28,465: 543262 [           main] ERROR            java.lang.Throwable -        ... 3 more
2017-11-08 23:19:28,473: 543270 [           main] ERROR            java.lang.Throwable - Caused by: org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [org.springframework.context.support.ClassPathXmlApplicationContext]: Constructor threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [spring/spring-context-database.xml]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: [PersistenceUnit: DefaultPersistenceUnit] Unable to build Hibernate SessionFactory
2017-11-08 23:19:28,492: 543289 [           main] ERROR            java.lang.Throwable -        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:163)
2017-11-08 23:19:28,508: 543305 [           main] ERROR            java.lang.Throwable -        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:121)
2017-11-08 23:19:28,515: 543312 [           main] ERROR            java.lang.Throwable -        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:277)
2017-11-08 23:19:28,521: 543318 [           main] ERROR            java.lang.Throwable -        ... 16 more
2017-11-08 23:19:28,523: 543320 [           main] ERROR            java.lang.Throwable - Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [spring/spring-context-database.xml]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: [PersistenceUnit: DefaultPersistenceUnit] Unable to build Hibernate SessionFactory
2017-11-08 23:19:28,539: 543336 [           main] ERROR            java.lang.Throwable -        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1514)
2017-11-08 23:19:28,547: 543344 [           main] ERROR            java.lang.Throwable -        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:521)
2017-11-08 23:19:28,564: 543361 [           main] ERROR            java.lang.Throwable -        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:458)
2017-11-08 23:19:28,570: 543367 [           main] ERROR            java.lang.Throwable -        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:293)
2017-11-08 23:19:28,578: 543375 [           main] ERROR            java.lang.Throwable -        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:223)
2017-11-08 23:19:28,584: 543381 [           main] ERROR            java.lang.Throwable -        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:290)
2017-11-08 23:19:28,590: 543387 [           main] ERROR            java.lang.Throwable -        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:191)
2017-11-08 23:19:28,596: 543393 [           main] ERROR            java.lang.Throwable -        at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1123)
2017-11-08 23:19:28,607: 543404 [           main] ERROR            java.lang.Throwable -        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:928)
2017-11-08 23:19:28,614: 543411 [           main] ERROR            java.lang.Throwable -        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:479)
2017-11-08 23:19:28,620: 543417 [           main] ERROR            java.lang.Throwable -        at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
2017-11-08 23:19:28,626: 543423 [           main] ERROR            java.lang.Throwable -        at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:93)
2017-11-08 23:19:28,632: 543429 [           main] ERROR            java.lang.Throwable -        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
2017-11-08 23:19:28,637: 543434 [           main] ERROR            java.lang.Throwable -        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
2017-11-08 23:19:28,642: 543439 [           main] ERROR            java.lang.Throwable -        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
2017-11-08 23:19:28,649: 543446 [           main] ERROR            java.lang.Throwable -        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
2017-11-08 23:19:28,654: 543451 [           main] ERROR            java.lang.Throwable -        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:148)
2017-11-08 23:19:28,659: 543456 [           main] ERROR            java.lang.Throwable -        ... 18 more
2017-11-08 23:19:28,663: 543460 [           main] ERROR            java.lang.Throwable - Caused by: javax.persistence.PersistenceException: [PersistenceUnit: DefaultPersistenceUnit] Unable to build Hibernate SessionFactory
2017-11-08 23:19:28,673: 543470 [           main] ERROR            java.lang.Throwable -        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.persistenceException(EntityManagerFactoryBuilderImpl.java:877)
2017-11-08 23:19:28,680: 543477 [           main] ERROR            java.lang.Throwable -        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:805)
2017-11-08 23:19:28,690: 543487 [           main] ERROR            java.lang.Throwable -        at org.hibernate.jpa.HibernatePersistenceProvider.createContainerEntityManagerFactory(HibernatePersistenceProvider.java:135)
2017-11-08 23:19:28,697: 543494 [           main] ERROR            java.lang.Throwable -        at org.hibernate.ejb.HibernatePersistence.createContainerEntityManagerFactory(HibernatePersistence.java:50)
2017-11-08 23:19:28,702: 543499 [           main] ERROR            java.lang.Throwable -        at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:290)
2017-11-08 23:19:28,709: 543506 [           main] ERROR            java.lang.Throwable -        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:310)
2017-11-08 23:19:28,717: 543514 [           main] ERROR            java.lang.Throwable -        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1573)
2017-11-08 23:19:28,730: 543527 [           main] ERROR            java.lang.Throwable -        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1511)
2017-11-08 23:19:28,738: 543535 [           main] ERROR            java.lang.Throwable -        ... 34 more
2017-11-08 23:19:28,741: 543538 [           main] ERROR            java.lang.Throwable - Caused by: org.hibernate.exception.GenericJDBCException: Unable to obtain JDBC Connection
2017-11-08 23:19:28,753: 543550 [           main] ERROR            java.lang.Throwable -        at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:47)
2017-11-08 23:19:28,758: 543555 [           main] ERROR            java.lang.Throwable -        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:109)
2017-11-08 23:19:28,765: 543562 [           main] ERROR            java.lang.Throwable -        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:95)
2017-11-08 23:19:28,771: 543568 [           main] ERROR            java.lang.Throwable -        at org.hibernate.tool.schema.extract.internal.ExtractionContextImpl.getJdbcConnection(ExtractionContextImpl.java:65)
2017-11-08 23:19:28,777: 543574 [           main] ERROR            java.lang.Throwable -        at org.hibernate.tool.schema.extract.internal.SequenceInformationExtractorH2DatabaseImpl.extractMetadata(SequenceInformationExtractorH2DatabaseImpl.java:35)
2017-11-08 23:19:28,785: 543582 [           main] ERROR            java.lang.Throwable -        at org.hibernate.tool.schema.extract.internal.DatabaseInformationImpl.initializeSequences(DatabaseInformationImpl.java:64)
2017-11-08 23:19:28,792: 543589 [           main] ERROR            java.lang.Throwable -        at org.hibernate.tool.schema.extract.internal.DatabaseInformationImpl.<init>(DatabaseInformationImpl.java:60)
2017-11-08 23:19:28,800: 543597 [           main] ERROR            java.lang.Throwable -        at org.hibernate.tool.hbm2ddl.SchemaUpdate.execute(SchemaUpdate.java:119)
2017-11-08 23:19:28,806: 543603 [           main] ERROR            java.lang.Throwable -        at org.hibernate.tool.hbm2ddl.SchemaUpdate.execute(SchemaUpdate.java:97)
2017-11-08 23:19:28,812: 543609 [           main] ERROR            java.lang.Throwable -        at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:481)
2017-11-08 23:19:28,820: 543617 [           main] ERROR            java.lang.Throwable -        at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:444)
2017-11-08 23:19:28,825: 543622 [           main] ERROR            java.lang.Throwable -        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:802)
2017-11-08 23:19:28,832: 543629 [           main] ERROR            java.lang.Throwable -        ... 40 more
2017-11-08 23:19:28,837: 543634 [           main] ERROR            java.lang.Throwable - Caused by: java.sql.SQLException: Connections could not be acquired from the underlying database!
2017-11-08 23:19:28,847: 543644 [           main] ERROR            java.lang.Throwable -        at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:118)
2017-11-08 23:19:28,852: 543649 [           main] ERROR            java.lang.Throwable -        at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutPooledConnection(C3P0PooledConnectionPool.java:692)
2017-11-08 23:19:28,858: 543655 [           main] ERROR            java.lang.Throwable -        at com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource.getConnection(AbstractPoolBackedDataSource.java:140)
2017-11-08 23:19:28,865: 543662 [           main] ERROR            java.lang.Throwable -        at org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl.getConnection(DatasourceConnectionProviderImpl.java:122)
2017-11-08 23:19:28,872: 543669 [           main] ERROR            java.lang.Throwable -        at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator$ConnectionProviderJdbcConnectionAccess.obtainConnection(JdbcEnvironmentInitiator.java:180)
2017-11-08 23:19:28,884: 543681 [           main] ERROR            java.lang.Throwable -        at org.hibernate.tool.schema.extract.internal.ExtractionContextImpl.getJdbcConnection(ExtractionContextImpl.java:62)
2017-11-08 23:19:28,892: 543689 [           main] ERROR            java.lang.Throwable -        ... 48 more
2017-11-08 23:19:28,894: 543691 [           main] ERROR            java.lang.Throwable - Caused by: com.mchange.v2.resourcepool.CannotAcquireResourceException: A ResourcePool could not acquire a resource from its primary factory or source.
2017-11-08 23:19:28,906: 543703 [           main] ERROR            java.lang.Throwable -        at com.mchange.v2.resourcepool.BasicResourcePool.awaitAvailable(BasicResourcePool.java:1469)
2017-11-08 23:19:28,913: 543710 [           main] ERROR            java.lang.Throwable -        at com.mchange.v2.resourcepool.BasicResourcePool.prelimCheckoutResource(BasicResourcePool.java:644)
2017-11-08 23:19:28,922: 543719 [           main] ERROR            java.lang.Throwable -        at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:554)
2017-11-08 23:19:28,928: 543725 [           main] ERROR            java.lang.Throwable -        at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutAndMarkConnectionInUse(C3P0PooledConnectionPool.java:758)
2017-11-08 23:19:28,934: 543731 [           main] ERROR            java.lang.Throwable -        at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutPooledConnection(C3P0PooledConnectionPool.java:685)
2017-11-08 23:19:28,940: 543737 [           main] ERROR            java.lang.Throwable -        ... 52 more
```

**Comment by ivansenic** [comment]
This looks very strange. Are you sure that there is no another running instance of the CMR on the same machine already? This error could be displayed in such situations. Have you at all managed to start the CMR after installing?

**Comment by charly13887** [comment]
Yes only 1 CMR instance is running on machine.
Till now not able to Start CMR on my machine. Earlier was getting exception related to Port, but after changing default port from 8182 to 8282, getting this exception.

**Comment by ivansenic** [comment]
@charly13887,

I checked this locally, changing port to 8282 does not result in the problem.

Can you check two things please:
1. Is the folder [CMR]/db created at all during this try to start-up?
2. Does the user that you use to start the CMR has write and read permissions for the [CMR]/ folder?

**Comment by charly13887** [comment]
@ivansenic,

Thanks for the suggestions. The issue is resolved now. It was due to write and read permissions.
Once I have granted all permission to that folder, it worked.

Cheers!!
