### ISSUE TITLE
Problem with future tasks

### ISSUE THREAD

**Issue by scoopex** [inspectIT/inspectIT#397]
I use inspectit 1.8.5.101 with openjdk 1.7.0_151 with tomcat 7.0.56 (yeah, i am performing software archaeology :-))

My application makes heavy use of java future tasks. Instrumentation fails with the following exceptions. The classes which caused the exception are not working with a activated inspectit java agent.

From my point of view java profiling tools : 
- should never break applications, because this creates fear of using it in production
- should support future tasks, because many application use it to improve execution times

Is there a workaround?
Can i help you to inspect this problem situation?

The exceptions look like this:
```
2018-07-24 02:36:03 +0000 DEBUG [http-nio-8443-exec-11] [550eb610-a8cb-446a-b64a-213ee71ada94] [] com.obfuscated.dashboard.services.impl.CachedTaskExecutor:128 - ExecutorService - QueueSize: 0, Active: 2, MaxPoolSize:
 5
Exception in thread "TaskThreadPool-1-thread-3" Exception in thread "TaskThreadPool-1-thread-4" java.lang.ClassCastException: rocks.inspectit.agent.java.tracing.core.async.executor.SpanStoreRunnable cannot be ca
st to java.util.concurrent.FutureTask
        at com.obfuscated.dashboard.tasks.TaskThreadPoolExecutor.beforeExecute(TaskThreadPoolExecutor.java:23)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
        at java.lang.Thread.run(Thread.java:748)
java.lang.ClassCastException: rocks.inspectit.agent.java.tracing.core.async.executor.SpanStoreRunnable cannot be cast to java.util.concurrent.FutureTask
        at com.obfuscated.dashboard.tasks.TaskThreadPoolExecutor.beforeExecute(TaskThreadPoolExecutor.java:23)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
        at java.lang.Thread.run(Thread.java:748)
java.lang.ClassCastException: rocks.inspectit.agent.java.tracing.core.async.executor.SpanStoreRunnable cannot be cast to java.util.concurrent.FutureTask
        at com.obfuscated.dashboard.tasks.TaskThreadPoolExecutor.beforeExecute(TaskThreadPoolExecutor.java:23)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
        at java.lang.Thread.run(Thread.java:748)
2018-07-24 02:36:03 +0000 DEBUG [http-nio-8443-exec-6] [1921138a-3dbe-42be-999f-49529d6703b2] [] com.obfuscated.dashboard.services.impl.CachedTaskExecutor:84 - Nowhere cached - computing new result for FoobarPrTask,FoobarPrTask,-552094479 com.obfuscated.dashboard.tasks.FoobarPrTask@b8e6947
2018-07-24 02:36:03 +0000 DEBUG [http-nio-8443-exec-6] [1921138a-3dbe-42be-999f-49529d6703b2] [] com.obfuscated.dashboard.services.impl.CachedTaskExecutor:128 - ExecutorService - QueueSize: 1, Active: 1, MaxPoolSize: 5
Exception in thread "TaskThreadPool-1-thread-5" java.lang.ClassCastException: rocks.inspectit.agent.java.tracing.core.async.executor.SpanStoreRunnable cannot be cast to java.util.concurrent.FutureTask
        at com.obfuscated.dashboard.tasks.TaskThreadPoolExecutor.beforeExecute(TaskThreadPoolExecutor.java:23)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
        at java.lang.Thread.run(Thread.java:748)
2018-07-24 02:36:03 +0000 DEBUG [http-nio-8443-exec-24] [77f63cba-a296-4146-ba10-1f285e342eb3] [] com.obfuscated.dashboard.services.impl.CachedTaskExecutor:84 - Nowhere cached - computing new result for FoobarPrTask,FoobarPrTask,302568964 com.obfuscated.dashboard.tasks.FoobarPrTask@4b5d6018
Exception in thread "TaskThreadPool-1-thread-1" java.lang.ClassCastException: rocks.inspectit.agent.java.tracing.core.async.executor.SpanStoreRunnable cannot be cast to java.util.concurrent.FutureTask2018-07-24 02:36:03 +0000 DEBUG [http-nio-8443-exec-24] [77f63cba-a296-4146-ba10-1f285e342eb3] [] com.obfuscated.dashboard.services.impl.CachedTaskExecutor:128 - ExecutorService - QueueSize: 0, Active: 1, MaxPoolSize: 5

        at com.obfuscated.dashboard.tasks.TaskThreadPoolExecutor.beforeExecute(TaskThreadPoolExecutor.java:23)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
        at java.lang.Thread.run(Thread.java:748)
2018-07-24 02:36:03 +0000 DEBUG [http-nio-8443-exec-9] [43e085d3-f1a8-44be-8739-8a4e193d96f6] [] com.obfuscated.dashboard.services.impl.CachedTaskExecutor:84 - Nowhere cached - computing new result for FoobarPrTask,FoobarPrTask,130000061 com.obfuscated.dashboard.tasks.FoobarPrTask@2b141562
2018-07-24 02:36:03 +0000 DEBUG [http-nio-8443-exec-9] [43e085d3-f1a8-44be-8739-8a4e193d96f6] [] com.obfuscated.dashboard.services.impl.CachedTaskExecutor:128 - ExecutorService - QueueSize: 1, Active: 0, MaxPoolSize: 5
Exception in thread "TaskThreadPool-1-thread-7" java.lang.ClassCastException: rocks.inspectit.agent.java.tracing.core.async.executor.SpanStoreRunnable cannot be cast to java.util.concurrent.FutureTask
        at com.obfuscated.dashboard.tasks.TaskThreadPoolExecutor.beforeExecute(TaskThreadPoolExecutor.java:23)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by mariusoe** [comment]
Hi Marc,
as a workaround, you can disable the "Executor Correlation" profile which enables the executor correlation. When you have disabled this, the application should not be crashing anymore.

We need to debug this why the exception is happening.

**Comment by scoopex** [comment]
Hello Marius,

thanks for your  quick ans very useful response. My application now does a proper initialize and seems to work correctly..

Please let me know how to help you to find the source of the describe problem

Regards
Marc

**Comment by ivansenic** [comment]
Hi Marc,

I would like to know what's the real class name of `com.obfuscated.dashboard.tasks.TaskThreadPoolExecutor`  if possible. Or better, is this something you developed on your own or is it coming from some lib. That would be really helpful. And would be also nice to give us a piece of code on how are tasks submitted to the `Executor` (if possible).

I guess the main problem here is that our instrumentation rule is working with the `Executor` interface and not with the concrete classes. This way we instrument all Executors, but potentially also the ones that have different ways of handling the `submit` method. We need to change this, so I also consider this a bug from our side!

**Comment by scoopex** [comment]
Submitted example classes directly per mail :-)

**Comment by ivansenic** [comment]
We will keep our profiles as they are. The bug relates to the custom created Executor that makes an unchecked cast from `Runnable` to `RunnableFuture`.

Solution:

- deactivate the `Executor correlation` common profile
- alternatively create a similar profile that instruments the concrete class(es) instead of all via interface correlation. For example, go for `java.util.concurrent.AbstractExecutorService`.
