### ISSUE TITLE
Buffer Underflow on CMR

### ISSUE THREAD

**Issue by gaganaroraitm** [inspectIT/inspectIT#400]
Hi,

I'm using 1.8.5.101 version of InspectIT. While instrumenting classes of package and it's subpackage (total no of classes should be around 10), I'm constantly getting following errors on agent:

`2018-09-18 23:45:50,498: 360246 [ruptor-thread-0] WARN  va.stats.AgentStatisticsLogger - Monitoring data is dropped due to buffer capacity reached or connection failure. Current count of dropped data is 100.
2018-09-18 23:45:51,981: 1274312 [ruptor-thread-0] WARN  va.stats.AgentStatisticsLogger - Monitoring data is dropped due to buffer capacity reached or connection failure. Current count of dropped data is 8045.
2018-09-18 23:46:00,908: 1283239 [ervice-thread-0] INFO  nnection.impl.KeepAliveManager - Trying to reconnect to the server.
2018-09-18 23:46:00,995: 1283326 [ervice-thread-0] INFO  nection.impl.KryoNetConnection - KryoNet: Reconnection successful!
2018-09-18 23:46:01,628: 371376 [ervice-thread-1] INFO  nnection.impl.KeepAliveManager - Trying to reconnect to the server.
2018-09-18 23:46:01,648: 371396 [ervice-thread-1] INFO  nection.impl.KryoNetConnection - KryoNet: Reconnection successful!
2018-09-18 23:46:08,669: 378417 [t-sa-executor-8] WARN  analyzer.impl.ByteCodeAnalyzer - Error occurred instrumenting the byte code of class org.hibernate.engine.internal.EntityEntryContext$1. Sending the class structure to the CMR resulted in a time-out.
java.util.concurrent.TimeoutException: null
        at java.util.concurrent.FutureTask.get(FutureTask.java:205)
        at rocks.inspectit.agent.java.analyzer.impl.ByteCodeAnalyzer.analyzeAndInstrumentInternal(ByteCodeAnalyzer.java:205)
        at rocks.inspectit.agent.java.analyzer.impl.ByteCodeAnalyzer.analyzeAndInstrument(ByteCodeAnalyzer.java:141)
        at rocks.inspectit.agent.java.SpringAgent.inspectByteCode(SpringAgent.java:233)
        at rocks.inspectit.agent.java.javaagent.JavaAgent.transform(JavaAgent.java:161)
        at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
`
And then agent hangs and status I get is No keep-alive signal on UI.

On CMR end the exception is:
`2018-09-18 23:43:58,430: 385187 [         Server] INFO  all.minlog.MinlogToSLF4JLogger - kryonet: Connection 33 connected: /10.127.126.40
2018-09-18 23:43:58,895: 385652 [ervice-thread-1] WARN  tExtendedByteBufferInputStream - Socket read runnable can not get the empty buffer to write to, aborting read.
2018-09-18 23:44:01,529: 388286 [         Server] ERROR all.minlog.MinlogToSLF4JLogger - kryonet: Error reading TCP from connection: Connection 33
com.esotericsoftware.kryo.KryoException: Buffer underflow.
Serialization trace:
timerData (rocks.inspectit.shared.all.communication.data.InvocationSequenceData)
nestedSequences (rocks.inspectit.shared.all.communication.data.InvocationSequenceData)
nestedSequences (rocks.inspectit.shared.all.communication.data.InvocationSequenceData)
        at com.esotericsoftware.kryo.io.Input.require(Input.java:181)
        at com.esotericsoftware.kryo.io.Input.skip(Input.java:137)
        at com.esotericsoftware.kryo.io.InputChunked.nextChunks(InputChunked.java:85)
        at rocks.inspectit.shared.all.serializer.impl.CustomCompatibleFieldSerializer.read(CustomCompatibleFieldSerializer.java:208)
        at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:679)
        at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:106)
        at rocks.inspectit.shared.all.serializer.impl.CustomCompatibleFieldSerializer.read(CustomCompatibleFieldSerializer.java:207)
        at rocks.inspectit.shared.all.serializer.impl.InvocationSequenceCustomCompatibleFieldSerializer.read(InvocationSequenceCustomCompatibleFieldSerializer.java:40)
        at rocks.inspectit.shared.all.serializer.impl.InvocationSequenceCustomCompatibleFieldSerializer.read(InvocationSequenceCustomCompatibleFieldSerializer.java:16)
`

Could you please help in fixing the issue? I'm using all defaults. But CMR is running with 4.5g of heap with young generation as 1.5g.

**Comment by ivansenic** [comment]
Is this happening constantly? Seems that your CMR cannot cope with all the data send by the agent.. What's the load that you have on the agent? How many agents are connected?

You can try to increase the direct memory given to the CMR, as this will allow more direct memory space to be used for the communication: `-XX:MaxDirectMemorySize=`..

**Comment by gaganaroraitm** [comment]
Thanks for the reply @ivansenic .

Yes, this is happening constantly. I have three instances of a service connected as an agent to the CMR. In CMR, I've a Remote Manual Server Sensor and a Timer Sensor and trying to instrument few classes (around 5) in  a package. 
I've tried assigning Direct Memory on CMR and agent side but with no luck.

**Comment by gaganaroraitm** [comment]
Could you please point to any article or documentation to tune and configure CMR & agent. I was trying to set up InspectIT on another environment and CMR is crashing constantly there.

Any quick help is appreciated.

**Comment by ivansenic** [comment]
Hey @gaganaroraitm,

I don't understand what is really your setup. You said you have a total of 3 agents and each instrumenting only a few classes, right? What does this mean:

> Each invocation of a service takes around 2 seconds and there are few thousand requests that are in pipeline.

Currently, inspectIT collects trace with each request, so having few thousand requests fired in 2 seconds (as I understand) could be maybe too much for inspectIT. Or did I got this wrong? Where is CMR actually crashing?

Yes, we are aware that this is shitty, but we are working on the updates there and the way better support around scaling. The current version has non-scalable CMR and quite an aggressive data collection on the agent. This will change in the future.

**Comment by gaganaroraitm** [comment]
Hi @ivansenic,

Thanks a lot for the information.
Is there any workaround to the problem? We're stuck and not able to proceed with the instrumentation. It would be a great push to our project to have an APM tool. 
Also, is there any tentative timeline for 1.9.2?

Thanks & Regards,
Gagan

**Comment by ivansenic** [comment]
I will release the 1.9.2 tomorrow with the fix.

**Comment by gaganaroraitm** [comment]
Great. Thanks a lot for your assistance.

**Comment by ivansenic** [comment]
Fixed in #401

**Comment by ivansenic** [comment]
Further fix in #407
