### ISSUE TITLE
CRM has HTTP ERROR 403

### ISSUE THREAD

**Issue by zakabluk** [inspectIT/inspectIT#406]
Hi! When I launched CRM via docker
sudo docker run -d --name inspectIT-CMR -p 8182:8182 -p 9070:9070 inspectit/cmr
and on windows server. But I have had one errors for both variants(try open http://127.0.0.1:8182).
```
HTTP ERROR 403
Problem accessing /. Reason:
    FORBIDDEN
Powered by Jetty://
```
Widows logs has
```
2018-11-27 00:13:19,380: 15401  [           main] INFO      rocks.inspectit.server.CMR - Starting CMR in version 1.9.2.106. Please note that inspectIT does not provide any guarantee on backwards compatibility. Only if the version match exactly we ensure that the components are compatible.
2018-11-27 00:13:19,384: 15405  [           main] INFO      rocks.inspectit.server.CMR - CMR started in 15074.346195 ms
2018-11-27 00:17:13,286: 249307 [         Server] INFO  all.minlog.MinlogToSLF4JLogger - kryonet: Connection 1 connected: /127.0.0.1
2018-11-27 00:17:13,300: 249321 [         Server] INFO  all.minlog.MinlogToSLF4JLogger - kryonet: Connection 2 connected: /127.0.0.1
2018-11-27 00:17:23,508: 259529 [         Server] WARN  tExtendedByteBufferInputStream - Read failed, can not get full byte buffer.
rocks.inspectit.shared.all.storage.nio.stream.AbstractExtendedByteBufferInputStream$ReadFailedException: Time-out trying to get the full byte buffer to read after 10 sec.
        at rocks.inspectit.shared.all.storage.nio.stream.AbstractExtendedByteBufferInputStream.bufferChange(AbstractExtendedByteBufferInputStream.java:271)
        at rocks.inspectit.shared.all.storage.nio.stream.AbstractExtendedByteBufferInputStream.read(AbstractExtendedByteBufferInputStream.java:227)
        at com.esotericsoftware.kryo.io.Input.fill(Input.java:146)
        at com.esotericsoftware.kryo.io.Input.require(Input.java:178)
        at com.esotericsoftware.kryo.io.Input.readVarInt(Input.java:355)
        at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:109)
        at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:641)
        at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:752)
        at rocks.inspectit.shared.all.kryonet.ExtendedSerializationImpl.read(ExtendedSerializationImpl.java:163)
        at rocks.inspectit.shared.all.kryonet.TcpConnection.readObject(TcpConnection.java:209)
        at rocks.inspectit.shared.all.kryonet.Server.update(Server.java:256)
        at rocks.inspectit.shared.all.kryonet.Server.run(Server.java:452)
        at java.lang.Thread.run(Thread.java:748)
2018-11-27 00:17:23,511: 259532 [         Server] ERROR all.minlog.MinlogToSLF4JLogger - kryonet: Error reading TCP from connection: Connection 1
```
Docker has
```
2018-11-26 21:51:23,629: 10426  [           main] INFO      rocks.inspectit.server.CMR - Starting CMR in version 1.9.2.106. Please note that inspectIT does not provide any guarantee on backwards compatibility. Only if the version match exactly we ensure that the components are compatible.
2018-11-26 21:51:23,629: 10426  [           main] INFO      rocks.inspectit.server.CMR - CMR started in 10162.860069 ms

```

**Comment by ivansenic** [comment]
Hi @zakabluk ,

The CMR does not offer the web-based UI. This is why visiting the `localhost:8182` results in the forbidden response. You need to use the inspectIT UI in order to visualize the data.

Cheers,
Ivan

**Comment by zakabluk** [comment]
ok. Thenx.
