### ISSUE TITLE
Getting Agent will not be active while starting the java application

### ISSUE THREAD

**Issue by nayanan-agi** [inspectIT/inspectIT#421]
Getting below exception while starting the application 
2024-04-10 14:39:07,978: 369    [           main] ERROR spectit.agent.java.SpringAgent - inspectIT agent initialization failed. Agent will not be active.
java.lang.ClassNotFoundException: java.sql.SQLException
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
	at rocks.inspectit.agent.java.javaagent.JavaAgent$InspectItClassLoader.loadClass(JavaAgent.java:550)
	at rocks.inspectit.agent.java.javaagent.JavaAgent$InspectItClassLoader.loadClass(JavaAgent.java:521)
	... 27 common frames omitted

DETAILS:
I am using latest version of agent,CMR and UI which is [Version 1.9.3](https://github.com/inspectIT/inspectIT/releases/tag/1.9.3.107)
-javaagent:C:/inspectIT/agent/inspectit-agent.jar -Dinspectit.repository=localhost:8132
-Dinspectit.agent.name=appName

**Comment by nayanan-agi** [comment]
[exceptions.log](https://github.com/inspectIT/inspectIT/files/14942034/exceptions.log)
